### Student create

POST localhost:8080/student/create
Content-Type: application/json

{
  "name": "Tosmat" ,
  "surname": "Qoziyev"
}

### Student get All
GET localhost:8080/student

### Student byId
GET localhost:8080/student/3

### Student update
PUT localhost:8080/student/3
Content-Type: application/json

{
  "name": "Qozi " ,
  "surname": "Qoziyev"
}

### Student delete
DELETE localhost:8080/student/6