### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Student create

POST localhost:8080/student/create
Content-Type: application/json

{
  "name": "alish32" ,
  "surname": "Mazgiyev1"
}